
package Vista;

public class Menu_Interfaz extends javax.swing.JFrame {

    public Menu_Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menu Interfaz");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIngredientes = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnVerReceta = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDeslogeo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngredientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIngredientes.setText("Ingredientes");
        btnIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngredientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 190, 100));

        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCrear.setText("Crear Torta");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 190, 100));

        btnVerReceta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVerReceta.setText("Ver Receta");
        btnVerReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRecetaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 190, 100));

        btnPedido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPedido.setText("Pedido");
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 190, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("D´ZOILA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, 130));

        btnDeslogeo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDeslogeo.setText("Cerrar Sesion");
        btnDeslogeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeslogeoActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeslogeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 220, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Crear_Receta ventana3 = new Crear_Receta();
        ventana3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientesActionPerformed
        Ingredientes ventana4 = new Ingredientes();
        ventana4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIngredientesActionPerformed

    private void btnVerRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRecetaActionPerformed
        Ver_Receta ventana5 = new Ver_Receta();
        ventana5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVerRecetaActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        Pedido ventana6 = new Pedido();
        ventana6.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnDeslogeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeslogeoActionPerformed
        Login ventana1 = new Login();
        this.setVisible(false);
    }//GEN-LAST:event_btnDeslogeoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDeslogeo;
    private javax.swing.JButton btnIngredientes;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnVerReceta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
